/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData emo_happy = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData soil_0 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData soil_25 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData soil_50 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData soil_75 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData soil_100 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData emo_thumbsup = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData emo_sleep = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData emo_unhappy = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData emo_wink = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData emo_surprised = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData emo_tongue = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData emo_coffee = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData emo_sunglasses = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData emo_displeased = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData emo_saint = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData emo_grin = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData emo_squint = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData emo_laugh = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData water_amount_large = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData water_amount_medium = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData water_amount_small = const IconData(0xe816, fontFamily: _kFontFam);
}
